//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.MyDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hczdbEntities : DbContext
    {
        public hczdbEntities()
            : base("name=hczdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_categories> tbl_categories { get; set; }
        public virtual DbSet<tbl_productDetail> tbl_productDetail { get; set; }
        public virtual DbSet<tbl_subcategories> tbl_subcategories { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
        public virtual DbSet<tbl_wishList> tbl_wishList { get; set; }
        public virtual DbSet<tbl_alert> tbl_alert { get; set; }
        public virtual DbSet<tbl_forgetPass> tbl_forgetPass { get; set; }
    }
}
