//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.MyDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_subcategories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_subcategories()
        {
            this.tbl_productDetail = new HashSet<tbl_productDetail>();
        }
    
        public decimal subcat_id { get; set; }
        public Nullable<decimal> cat_id { get; set; }
        public string subcat_name { get; set; }
        public string subcat_image { get; set; }
    
        public virtual tbl_categories tbl_categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_productDetail> tbl_productDetail { get; set; }
    }
}
