//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.MyDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_wishList
    {
        public decimal id { get; set; }
        public Nullable<decimal> ad_id { get; set; }
    
        public virtual tbl_productDetail tbl_productDetail { get; set; }
    }
}
