//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.MyDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_alert
    {
        public decimal aid { get; set; }
        public string sname { get; set; }
        public string smob { get; set; }
        public string semail { get; set; }
        public string sub { get; set; }
        public string msg { get; set; }
        public Nullable<decimal> rId { get; set; }
    }
}
