//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.MyDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_user()
        {
            this.tbl_productDetail = new HashSet<tbl_productDetail>();
        }
    
        public decimal user_id { get; set; }
        public string user_name { get; set; }
        public string user_email { get; set; }
        public string user_pass { get; set; }
        public string user_add { get; set; }
        public string user_locality { get; set; }
        public string user_city { get; set; }
        public Nullable<decimal> user_pincode { get; set; }
        public string user_mob_no { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_productDetail> tbl_productDetail { get; set; }
    }
}
